name: MSIBuilder

on:
  release:
    types: [published]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add WiX toolset
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        $url = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip"
        $outpath = "$PSScriptRoot/wix311-binaries.zip"
        Invoke-WebRequest -Uri $url -OutFile $outpath
        Expand-Archive $PSScriptRoot\wix311-binaries.zip -DestinationPath $PSScriptRoot\wix311
       

    - name: Copy files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: | 
        Expand-Archive telegraf.zip -DestinationPath $PSScriptRoot
        Copy-Item -Path build-ms.bat -Destination $PSScriptRoot

    - name: Build wixobj
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: | 
        & "$PSScriptRoot/wix311/candle.exe" -nologo telegraf.wxs -out $PSScriptRoot/telegraf.wixobj
        dir $PSScriptRoot

    - name: Build msi
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: | 
        & "$PSScriptRoot/wix311/light.exe" -nologo "$PSScriptRoot/telegraf.wixobj" -out $PSScriptRoot/telegraf.msi
        dir $PSScriptRoot

    - name: upload artifact
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: D:\a\_temp\telegraf.msi
